### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by javeedrahman** [HansSchouten/PHPagebuilder-boilerplate#1]
I have installed PHPagebuilder-boilerplate.

I have used both composer and without composer but i am getting "Page not Found" in both type.

Could you please help me?

**Comment by HansSchouten** [comment]
Did you login via /admin and create a page?

**Comment by javeedrahman** [comment]
i have not created any page, when i try routing to admin i am getting error.

https://prnt.sc/rdsvrf

Am i doing anything wrong anything i have missed?

**Comment by HansSchouten** [comment]
It might be related to the environment you are installing this in (or how .htaccess is parsed). You can check whether the `index.php` you created is executed and correctly creates an PHPageBuilder instance.

**Comment by inmanturbo** [comment]
so this will only work with apache

**Comment by HansSchouten** [comment]
Hmm you are correct, it fully relies on .htaccess now. I was already thinking about changing the boilerplate, so will take this into consideration.
